import type { Chapter, Question, Admin, Settings } from './types';

export const sampleChapters: Chapter[] = [
  { id: 'ch1', name: 'Electric Charges & Fields', description: 'Electric charges, Coulomb law, electric field, electric dipole, Gauss law.', topics: ['Electric Charge', 'Coulomb Law', 'Electric Field', 'Electric Dipole', 'Gauss Law'], order: 1, active: true },
  { id: 'ch2', name: 'Electrostatic Potential & Capacitance', description: 'Electric potential, potential energy, capacitors, dielectrics.', topics: ['Electric Potential', 'Potential Energy', 'Capacitors', 'Parallel Plate Capacitor', 'Dielectrics'], order: 2, active: true },
  { id: 'ch3', name: 'Current Electricity', description: 'Electric current, Ohm law, resistance, Kirchhoff laws, Wheatstone bridge.', topics: ['Electric Current', 'Ohm Law', 'Resistance', 'Kirchhoff Laws', 'Wheatstone Bridge', 'Meter Bridge'], order: 3, active: true },
  { id: 'ch4', name: 'Moving Charges & Magnetism', description: 'Magnetic force, motion in magnetic field, Biot-Savart law, Ampere law.', topics: ['Lorentz Force', 'Cyclotron', 'Biot-Savart Law', 'Ampere Law', 'Solenoid', 'Torque on Coil'], order: 4, active: true },
  { id: 'ch5', name: 'Magnetism & Matter', description: 'Magnetic dipoles, magnetization, magnetic materials, hysteresis.', topics: ['Magnetic Dipole', 'Bar Magnet', 'Magnetization', 'Magnetic Materials', 'Hysteresis'], order: 5, active: true },
  { id: 'ch6', name: 'Electromagnetic Induction', description: 'Faraday law, Lenz law, self and mutual induction, eddy currents.', topics: ['Faraday Law', 'Lenz Law', 'Self Induction', 'Mutual Induction', 'Eddy Currents', 'AC Generator'], order: 6, active: true },
  { id: 'ch7', name: 'Alternating Current', description: 'AC voltage, impedance, resonance, power in AC circuits, transformer.', topics: ['AC Voltage', 'Impedance', 'LCR Circuit', 'Resonance', 'Power Factor', 'Transformer'], order: 7, active: true },
  { id: 'ch8', name: 'Electromagnetic Waves', description: 'EM wave spectrum, properties, Maxwell equations.', topics: ['EM Spectrum', 'Maxwell Equations', 'Properties of EM Waves', 'EM Wave Propagation'], order: 8, active: true },
  { id: 'ch9', name: 'Ray Optics', description: 'Reflection, refraction, lenses, optical instruments, dispersion.', topics: ['Reflection', 'Refraction', 'Total Internal Reflection', 'Lenses', 'Optical Instruments', 'Dispersion'], order: 9, active: true },
  { id: 'ch10', name: 'Wave Optics', description: 'Interference, diffraction, polarization, Young double slit.', topics: ['Interference', 'Young Double Slit', 'Diffraction', 'Polarization', 'Malus Law'], order: 10, active: true },
  { id: 'ch11', name: 'Dual Nature of Radiation & Matter', description: 'Photoelectric effect, de Broglie wavelength, electron emission.', topics: ['Photoelectric Effect', 'Einstein Equation', 'de Broglie Wavelength', 'Wave-Particle Duality'], order: 11, active: true },
  { id: 'ch12', name: 'Atoms', description: 'Bohr model, atomic spectra, energy levels.', topics: ['Bohr Model', 'Energy Levels', 'Atomic Spectra', 'Hydrogen Atom'], order: 12, active: true },
  { id: 'ch13', name: 'Nuclei', description: 'Nuclear structure, radioactivity, nuclear energy, fission, fusion.', topics: ['Nuclear Structure', 'Radioactivity', 'Half Life', 'Nuclear Fission', 'Nuclear Fusion', 'Mass-Energy Relation'], order: 13, active: true },
  { id: 'ch14', name: 'Semiconductors', description: 'Intrinsic and extrinsic semiconductors, p-n junction, diode, transistor.', topics: ['Intrinsic Semiconductor', 'Extrinsic Semiconductor', 'p-n Junction', 'Diode', 'Transistor', 'Logic Gates'], order: 14, active: true },
];

function q(id: string, ch: string, text: string, opts: string[], correct: number, exp: string, diff: 'Easy'|'Medium'|'Hard', topic: string): Question {
  return { id, chapterId: ch, questionText: text, options: opts, correctOption: correct, explanation: exp, difficulty: diff, topic, active: true };
}

export const sampleQuestions: Question[] = [
  // Ch1: Electric Charges & Fields
  q('q1_1','ch1','The SI unit of electric charge is:',['Coulomb','Ampere','Volt','Ohm'],0,'The SI unit of electric charge is the coulomb (C).','Easy','Electric Charge'),
  q('q1_2','ch1','Like charges:',['Attract each other','Repel each other','Have no effect','Cancel each other'],1,'Like charges repel each other according to Coulomb law.','Easy','Electric Charge'),
  q('q1_3','ch1','Coulomb law is valid for:',['Point charges only','Distributed charges only','Both point and distributed','Neither'],2,'Coulomb law is valid for point charges.','Medium','Coulomb Law'),
  q('q1_4','ch1','The electric field inside a charged conductor is:',['Maximum','Minimum','Zero','Infinite'],2,'The electric field inside a charged conductor is zero in electrostatic equilibrium.','Easy','Electric Field'),
  q('q1_5','ch1','Gauss law relates electric flux to:',['Magnetic field','Enclosed charge','Current','Potential'],1,'Gauss law: total flux = enclosed charge / epsilon_0.','Medium','Gauss Law'),
  q('q1_6','ch1','The electric field on axial line of a dipole at distance r (r >> a) is proportional to:',['1/r^2','1/r^3','1/r','r^2'],1,'On axial line, E is proportional to 1/r^3 for r >> a.','Hard','Electric Dipole'),
  q('q1_7','ch1','Two charges +q and -q separated by d. E at midpoint is:',['Zero','From +q to -q','From -q to +q','Perpendicular to line'],1,'Both fields point from +q to -q at midpoint, they add up.','Medium','Electric Field'),
  q('q1_8','ch1','Electric flux through a closed surface enclosing charge q is:',['q','q/epsilon_0','epsilon_0/q','Zero'],1,'Gauss law: flux = q / epsilon_0.','Medium','Gauss Law'),
  q('q1_9','ch1','Torque on a dipole in uniform E is maximum when angle between p and E is:',['0 degrees','45 degrees','90 degrees','180 degrees'],2,'Torque = pE sin(theta). Max at theta = 90 degrees.','Medium','Electric Dipole'),
  q('q1_10','ch1','Electric field lines never:',['Start from positive charge','End at negative charge','Cross each other','Are closer where field is stronger'],2,'Electric field lines never cross each other.','Easy','Electric Field'),
  q('q1_11','ch1','A charge q at center of a cube. Flux through one face is:',['q/(6*epsilon_0)','q/epsilon_0','q/(3*epsilon_0)','q/(8*epsilon_0)'],0,'By symmetry, total flux q/epsilon_0 divided equally among 6 faces.','Medium','Gauss Law'),
  q('q1_12','ch1','If distance between two charges is doubled, force becomes:',['Half','One-fourth','Double','Four times'],1,'F proportional to 1/r^2. r doubles, F becomes 1/4th.','Easy','Coulomb Law'),
  q('q1_13','ch1','Potential energy of a dipole is minimum when:',['p parallel to E','p anti-parallel to E','p perpendicular to E','p at 45 degrees'],0,'U = -pE cos(theta). Min when cos(theta) = 1.','Hard','Electric Dipole'),
  q('q1_14','ch1','Charge on a body is always:',['Integer multiple of e','Fraction of e','Zero','Negative only'],0,'Quantization of charge: q = ne.','Medium','Electric Charge'),
  q('q1_15','ch1','A hollow metallic sphere is charged. E = 0 at:',['Outside only','Inside only','Both inside and outside','Neither'],1,'For a charged conductor, E = 0 inside.','Medium','Electric Field'),

  // Ch2: Electrostatic Potential & Capacitance
  q('q2_1','ch2','The unit of electric potential is:',['Volt','Coulomb','Newton','Joule'],0,'Electric potential is measured in volts (V).','Easy','Electric Potential'),
  q('q2_2','ch2','Equipotential surfaces are:',['Parallel to E field','Perpendicular to E field','At 45 degrees to field','Random'],1,'Equipotential surfaces are perpendicular to field lines.','Medium','Electric Potential'),
  q('q2_3','ch2','Capacitance of parallel plate capacitor (area A, separation d):',['epsilon_0*A/d','epsilon_0*d/A','A*d/epsilon_0','epsilon_0*A*d'],0,'C = epsilon_0 * A / d.','Easy','Capacitors'),
  q('q2_4','ch2','When dielectric is inserted between plates, capacitance:',['Decreases','Increases','Remains same','Becomes zero'],1,'Dielectric increases capacitance by factor k.','Easy','Dielectrics'),
  q('q2_5','ch2','Energy stored in a capacitor is:',['(1/2)CV^2','CV^2','(1/2)C^2V','2CV^2'],0,'U = (1/2)CV^2 = Q^2/(2C) = (1/2)QV.','Medium','Capacitors'),
  q('q2_6','ch2','Three capacitors 3F, 5F, 7F in series. Equivalent is:',['15F','15/105 F','105/71 F','1.53 F'],2,'1/C = 1/3+1/5+1/7 = 71/105, so C = 105/71 F.','Medium','Capacitors'),
  q('q2_7','ch2','Potential due to a negative charge is:',['Positive','Negative','Zero','Infinite'],1,'V = kq/r. For negative q, V is negative.','Easy','Electric Potential'),
  q('q2_8','ch2','Work done moving charge along equipotential surface is:',['Positive','Negative','Zero','Infinite'],2,'No work done along equipotential surface (V diff = 0).','Easy','Electric Potential'),
  q('q2_9','ch2','If V across capacitor is doubled, stored energy becomes:',['Doubled','Halved','Four times','Unchanged'],2,'U = (1/2)CV^2. V doubles, U becomes 4x.','Medium','Capacitors'),
  q('q2_10','ch2','Electrostatic PE of two charges q1,q2 separated by r:',['k*q1*q2/r','k*q1*q2/r^2','k*(q1+q2)/r','k*q1*q2*r'],0,'U = k*q1*q2/r.','Medium','Potential Energy'),
  q('q2_11','ch2','Capacitor 4F charged to 100V. Charge stored:',['25C','400C','200C','100C'],1,'Q = CV = 4 * 100 = 400 C.','Easy','Capacitors'),
  q('q2_12','ch2','E between parallel plates of a capacitor is:',['sigma/epsilon_0','sigma/(2*epsilon_0)','2*sigma/epsilon_0','zero'],0,'E = sigma/epsilon_0 between parallel plates.','Hard','Capacitors'),
  q('q2_13','ch2','Two capacitors in parallel: Ceq = :',['C1*C2/(C1+C2)','C1+C2','1/C1+1/C2','C1-C2'],1,'In parallel, Ceq = C1 + C2.','Easy','Capacitors'),
  q('q2_14','ch2','Isolated conducting sphere of radius R has capacitance:',['4*pi*epsilon_0*R','epsilon_0/R','4*pi*epsilon_0/R','R/(4*pi*epsilon_0)'],0,'C = 4*pi*epsilon_0*R for isolated sphere.','Hard','Capacitors'),
  q('q2_15','ch2','If dielectric removed from charged capacitor (battery disconnected):',['Energy increases','Energy decreases','Same','Charge increases'],0,'U = Q^2/(2C). C decreases, U increases.','Hard','Dielectrics'),

  // Ch3: Current Electricity
  q('q3_1','ch3','SI unit of electric current is:',['Ampere','Volt','Ohm','Coulomb'],0,'SI unit of current is ampere (A).','Easy','Electric Current'),
  q('q3_2','ch3','Ohm law states:',['V = IR','V = I/R','V = R/I','I = VR'],0,'Ohm law: V = IR.','Easy','Ohm Law'),
  q('q3_3','ch3','Resistivity of a conductor depends on:',['Length','Area','Material','Temperature and material'],3,'Resistivity is a material property depending on temperature.','Medium','Resistance'),
  q('q3_4','ch3','In a series circuit, current is:',['Same through all resistors','Different through each','Max through largest R','Zero'],0,'In series, current is the same through all components.','Easy','Resistance'),
  q('q3_5','ch3','Kirchhoff junction rule is based on conservation of:',['Energy','Charge','Momentum','Mass'],1,'Junction rule (KCL) is based on conservation of charge.','Medium','Kirchhoff Laws'),
  q('q3_6','ch3','Kirchhoff loop rule is based on conservation of:',['Energy','Charge','Momentum','Mass'],0,'Loop rule (KVL) is based on conservation of energy.','Medium','Kirchhoff Laws'),
  q('q3_7','ch3','Terminal voltage is less than EMF when:',['Cell is charging','Cell is discharging','No current flows','Circuit is open'],1,'During discharge, V = E - Ir, so V < E.','Medium','Electric Current'),
  q('q3_8','ch3','Wheatstone bridge is most sensitive when resistances are:',['Zero','Equal','Very large','Very small'],1,'Most sensitive when all four arms have equal resistance.','Medium','Wheatstone Bridge'),
  q('q3_9','ch3','Drift velocity of electrons is proportional to:',['Electric field','Square of E field','Inverse of E field','Independent of E'],0,'vd = eE*tau/m, proportional to E.','Medium','Electric Current'),
  q('q3_10','ch3','Two 6 ohm resistors in parallel: equivalent is:',['12 ohm','3 ohm','6 ohm','9 ohm'],1,'1/R = 1/6+1/6 = 1/3, so R = 3 ohm.','Easy','Resistance'),
  q('q3_11','ch3','A meter bridge works on:',['Ohm law','Wheatstone bridge','Kirchhoff law','Faraday law'],1,'Meter bridge is a practical Wheatstone bridge.','Easy','Wheatstone Bridge'),
  q('q3_12','ch3','Internal resistance of ideal ammeter is:',['Infinite','Zero','Very high','Depends on range'],1,'Ideal ammeter has zero resistance.','Easy','Electric Current'),
  q('q3_13','ch3','Internal resistance of ideal voltmeter is:',['Zero','Infinite','Very low','Depends on range'],1,'Ideal voltmeter has infinite resistance.','Easy','Electric Current'),
  q('q3_14','ch3','Resistivity of semiconductor with increase in temperature:',['Increases','Decreases','Same','Becomes zero'],1,'Semiconductors have negative temperature coefficient.','Medium','Resistance'),
  q('q3_15','ch3','Power dissipated in a resistor is:',['V^2/R','VR','V/R^2','V^2*R'],0,'P = V^2/R = I^2*R = VI.','Easy','Resistance'),
  q('q3_16','ch3','Potentiometer is superior to voltmeter for EMF because:',['Cheaper','Draws no current','Portable','Digital'],1,'Potentiometer draws no current at balance point.','Medium','Electric Current'),
  q('q3_17','ch3','Mobility of charge carriers is:',['Drift velocity per unit E','Current per unit area','Charge per unit volume','Energy per unit charge'],0,'Mobility = vd/E.','Medium','Electric Current'),
  q('q3_18','ch3','Wheatstone bridge balance condition:',['P/Q = R/S','P*Q = R*S','P+Q = R+S','P-Q = R-S'],0,'Balance: P/Q = R/S.','Easy','Wheatstone Bridge'),
  q('q3_19','ch3','EMF of a cell is best measured using:',['Ammeter','Voltmeter','Potentiometer','Galvanometer'],2,'Potentiometer gives most accurate EMF measurement.','Easy','Electric Current'),
  q('q3_20','ch3','Current density J is related to E by:',['J = sigma*E','J = E/sigma','J = sigma/E','J = E^2*sigma'],0,'J = sigma*E (Ohm law in microscopic form).','Medium','Resistance'),

  // Ch4: Moving Charges & Magnetism
  q('q4_1','ch4','Magnetic force on a moving charge is:',['Perpendicular to both v and B','Along v','Along B','Perpendicular to v only'],0,'F = qv x B is perpendicular to both v and B.','Easy','Lorentz Force'),
  q('q4_2','ch4','Path of charge moving perpendicular to uniform B is:',['Straight line','Parabola','Circle','Ellipse'],2,'Charge moving perpendicular to B follows circular path.','Medium','Lorentz Force'),
  q('q4_3','ch4','Biot-Savart law is analogous to:',['Gauss law','Coulomb law','Faraday law','Ohm law'],1,'Biot-Savart for B field is analogous to Coulomb law for E field.','Medium','Biot-Savart Law'),
  q('q4_4','ch4','Magnetic field inside a long solenoid is:',['Zero','mu_0*n*I','mu_0*I/(2*pi*r)','mu_0*I/(4*pi*r)'],1,'B = mu_0*n*I inside a long solenoid.','Medium','Ampere Law'),
  q('q4_5','ch4','Ampere circuital law relates:',['B to enclosed current','E to enclosed charge','B to flux','E to current'],0,'Ampere law: integral B.dl = mu_0 * I_enclosed.','Medium','Ampere Law'),
  q('q4_6','ch4','Force between parallel conductors with same direction current:',['Repulsive','Attractive','Zero','Perpendicular'],1,'Parallel currents in same direction attract.','Medium','Ampere Law'),
  q('q4_7','ch4','Torque on a current loop in B field is:',['nIBA','nIB/A','nIB^2*A','nI/BA'],0,'Torque = nIBA sin(theta).','Medium','Solenoid'),
  q('q4_8','ch4','A cyclotron is used to:',['Measure current','Accelerate charged particles','Measure B field','Generate EM waves'],1,'Cyclotron accelerates charged particles.','Easy','Cyclotron'),
  q('q4_9','ch4','Radius of circular path of charge in B field:',['mv/(qB)','mvB/q','mq/(vB)','qB/(mv)'],0,'r = mv/(qB) from centripetal force balance.','Medium','Lorentz Force'),
  q('q4_10','ch4','B at center of circular coil of radius R with current I:',['mu_0*I/(2R)','mu_0*I/(2*pi*R)','mu_0*I/R','mu_0*I/(4*pi*R)'],0,'B = mu_0*I/(2R) at center of circular loop.','Medium','Biot-Savart Law'),
  q('q4_11','ch4','Magnetic moment of a current loop is:',['IA','I/A','I^2*A','I*A^2'],0,'Magnetic moment m = IA.','Easy','Torque on Coil'),
  q('q4_12','ch4','Work done by magnetic force on a moving charge:',['qvB','q(v x B)','Zero','qvBsin(theta)'],2,'Magnetic force is perpendicular to velocity, work = 0.','Medium','Lorentz Force'),
  q('q4_13','ch4','Moving coil galvanometer uses:',['Magnetic field','Electric field','Gravitational field','Nuclear force'],0,'Moving coil galvanometer works on magnetic torque.','Easy','Solenoid'),
  q('q4_14','ch4','SI unit of magnetic field:',['Gauss','Tesla','Weber','Henry'],1,'SI unit is Tesla (T).','Easy','Magnetic Field'),
  q('q4_15','ch4','Magnetic force does not change:',['Direction of velocity','Speed of particle','Kinetic energy','Both B and C'],3,'Magnetic force perpendicular to velocity, speed and KE constant.','Medium','Lorentz Force'),

  // Ch5: Magnetism & Matter
  q('q5_1','ch5','Magnetic field lines of a bar magnet:',['Start from S and end at N','Start from N and end at S','Are closed loops','Both B and C'],2,'Magnetic field lines form closed loops from N to S externally.','Easy','Magnetic Dipole'),
  q('q5_2','ch5','A diamagnetic material in a magnetic field is:',['Weakly attracted','Weakly repelled','Strongly attracted','Strongly repelled'],1,'Diamagnetic materials are weakly repelled.','Easy','Magnetic Materials'),
  q('q5_3','ch5','Magnetic susceptibility of paramagnetic material is:',['Large and negative','Small and negative','Small and positive','Large and positive'],2,'Paramagnetic materials have small positive susceptibility.','Medium','Magnetic Materials'),
  q('q5_4','ch5','Curie law: susceptibility is:',['Proportional to T','Inversely proportional to T','Independent of T','Proportional to T^2'],1,'Curie law: chi = C/T.','Medium','Magnetization'),
  q('q5_5','ch5','Iron is an example of:',['Diamagnetic','Paramagnetic','Ferromagnetic','Non-magnetic'],2,'Iron is ferromagnetic.','Easy','Magnetic Materials'),
  q('q5_6','ch5','Curie temperature of iron is approximately:',['770 C','100 C','273 C','1500 C'],0,'Curie temp of iron is about 770 C.','Medium','Magnetic Materials'),
  q('q5_7','ch5','Hysteresis loss is energy lost as:',['Electrical energy','Heat energy','Magnetic energy','Light energy'],1,'Hysteresis loss appears as heat.','Medium','Hysteresis'),
  q('q5_8','ch5','Area under B-H curve represents:',['Permeability','Susceptibility','Energy loss per cycle','Coercivity'],2,'Area of hysteresis loop = energy loss per cycle.','Hard','Hysteresis'),
  q('q5_9','ch5','A bar magnet is equivalent to:',['A solenoid','A capacitor','A resistor','A transformer'],0,'Bar magnet equivalent to current-carrying solenoid.','Easy','Bar Magnet'),
  q('q5_10','ch5','Retentivity is ability to:',['Resist magnetization','Retain magnetization after field removal','Conduct electricity','Generate B field'],1,'Retentivity = residual magnetization after field removal.','Medium','Hysteresis'),
  q('q5_11','ch5','Soft iron for electromagnets because:',['High retentivity','High coercivity','Low retentivity and coercivity','High susceptibility only'],2,'Soft iron has low retentivity and coercivity.','Hard','Magnetic Materials'),
  q('q5_12','ch5','Net magnetic moment of diamagnetic atom is:',['Very large','Small but non-zero','Zero','Negative'],2,'Diamagnetic atoms have zero net magnetic moment.','Medium','Magnetization'),
  q('q5_13','ch5','Above Curie temperature, ferromagnetic becomes:',['Diamagnetic','Paramagnetic','Superconducting','Non-magnetic'],1,'Above Curie temp, ferromagnets become paramagnetic.','Medium','Magnetic Materials'),
  q('q5_14','ch5','Horizontal component of earth B field at equator is:',['Zero','Maximum','Equal to B','Half of B'],1,'At magnetic equator, horizontal component = B (maximum).','Medium','Bar Magnet'),
  q('q5_15','ch5','Above Curie temperature, ferromagnetic becomes:',['Diamagnetic','Paramagnetic','Superconducting','Non-magnetic'],1,'Above Curie temp, ferromagnets become paramagnetic.','Medium','Magnetic Materials'),

  // Ch6: Electromagnetic Induction
  q('q6_1','ch6','Faraday law: induced EMF is:',['Proportional to rate of change of flux','Equal to magnetic flux','Proportional to flux','Zero'],0,'EMF = -d(phi)/dt.','Easy','Faraday Law'),
  q('q6_2','ch6','Lenz law gives:',['Magnitude of induced EMF','Direction of induced current','Energy of B field','Flux through coil'],1,'Lenz law determines direction of induced current.','Easy','Lenz Law'),
  q('q6_3','ch6','SI unit of magnetic flux:',['Tesla','Weber','Henry','Volt'],1,'Magnetic flux in Weber (Wb).','Easy','Faraday Law'),
  q('q6_4','ch6','Self inductance of solenoid depends on:',['Current only','Number of turns and geometry','Resistance only','Voltage only'],1,'Self inductance depends on N, A, l and core material.','Medium','Self Induction'),
  q('q6_5','ch6','Energy stored in an inductor:',['(1/2)LI^2','LI^2','(1/2)L^2I','2LI^2'],0,'U = (1/2)LI^2.','Medium','Self Induction'),
  q('q6_6','ch6','Eddy currents are:',['Currents in straight wire','Circular currents in bulk conductors','Currents in capacitor','Currents in vacuum'],1,'Eddy currents are circular currents induced in bulk conductors.','Easy','Eddy Currents'),
  q('q6_7','ch6','AC generator works on:',['Electrostatic induction','Electromagnetic induction','Coulomb law','Ohm law'],1,'AC generator works on EM induction.','Easy','AC Generator'),
  q('q6_8','ch6','Mutual inductance depends on:',['Current in first coil','Number of turns in both coils','Resistance of coils','Voltage applied'],1,'Mutual inductance depends on geometry and turns of both coils.','Medium','Mutual Induction'),
  q('q6_9','ch6','SI unit of inductance:',['Henry','Weber','Tesla','Farad'],0,'Unit of inductance is Henry (H).','Easy','Self Induction'),
  q('q6_10','ch6','When magnet is pushed into a coil, induced EMF depends on:',['Speed of magnet','Pole of magnet','Color of magnet','Size of coil only'],0,'Faster the magnet, greater the rate of flux change, larger EMF.','Medium','Faraday Law'),
  q('q6_11','ch6','Eddy currents are used in:',['Electromagnets','Induction furnaces','Transformers','Batteries'],1,'Eddy currents used in induction furnaces for heating.','Easy','Eddy Currents'),
  q('q6_12','ch6','Flux through N-turn coil changes from phi1 to phi2 in time t. EMF is:',['-N(phi2-phi1)/t','-N(phi1+phi2)/t','-N(phi2*phi1)/t','N(phi2-phi1)/t'],0,'EMF = -N * (phi2-phi1)/t.','Medium','Faraday Law'),
  q('q6_13','ch6','In ideal transformer:',['V1*I1 = V2*I2','V1*I2 = V2*I1','V1/V2 = I1/I2','V1*V2 = I1*I2'],0,'Ideal transformer: V1*I1 = V2*I2 (power conservation).','Medium','Mutual Induction'),
  q('q6_14','ch6','Motional EMF of rod (length l, velocity v, field B):',['Blv','B/lv','Bv/l','Bl/v'],0,'EMF = B*l*v.','Easy','Faraday Law'),
  q('q6_15','ch6','Lenz law is a consequence of conservation of:',['Charge','Energy','Momentum','Mass'],1,'Lenz law ensures induced current opposes change, conserving energy.','Medium','Lenz Law'),

  // Ch7: Alternating Current
  q('q7_1','ch7','RMS value of AC current is:',['I0/sqrt(2)','I0*sqrt(2)','I0/2','2*I0'],0,'Irms = I0/sqrt(2) for sinusoidal AC.','Easy','AC Voltage'),
  q('q7_2','ch7','In pure resistive AC circuit:',['Current leads voltage','Current lags voltage','Current in phase with voltage','Current is zero'],2,'In pure resistor, current and voltage are in phase.','Easy','Impedance'),
  q('q7_3','ch7','In pure inductive circuit:',['Current leads voltage by 90','Current lags voltage by 90','In phase','Current leads by 45'],1,'In pure inductor, current lags voltage by 90 degrees.','Medium','LCR Circuit'),
  q('q7_4','ch7','In pure capacitive circuit:',['Current leads voltage by 90','Current lags voltage by 90','In phase','Current lags by 45'],0,'In pure capacitor, current leads voltage by 90 degrees.','Medium','LCR Circuit'),
  q('q7_5','ch7','At resonance in LCR circuit:',['Impedance maximum','Impedance minimum','Current minimum','Power factor zero'],1,'At resonance, XL=XC, Z=R (minimum), I maximum.','Medium','Resonance'),
  q('q7_6','ch7','Power factor of pure inductor circuit:',['1','0','0.5','infinity'],1,'For pure inductor, phi=90, cos(90)=0.','Easy','Power Factor'),
  q('q7_7','ch7','Transformer works on:',['Self induction','Mutual induction','EM radiation','Electrostatic induction'],1,'Transformer works on mutual induction.','Easy','Transformer'),
  q('q7_8','ch7','Impedance of LCR circuit:',['R+XL+XC','sqrt(R^2+(XL-XC)^2)','sqrt(R^2+XL^2+XC^2)','R*XL*XC'],1,'Z = sqrt(R^2 + (XL-XC)^2).','Medium','Impedance'),
  q('q7_9','ch7','Average power in AC circuit:',['Vrms*Irms','Vrms*Irms*cos(phi)','Vrms*Irms*sin(phi)','V0*I0'],1,'Pavg = Vrms*Irms*cos(phi).','Medium','Power Factor'),
  q('q7_10','ch7','Step-up transformer:',['Increases V, decreases I','Decreases V, increases I','Increases both','Decreases both'],0,'Step-up increases V and decreases I (P=VI conserved).','Easy','Transformer'),
  q('q7_11','ch7','Resonant frequency of LCR circuit:',['1/(2*pi*sqrt(LC))','1/(2*pi*LC)','2*pi*sqrt(LC)','sqrt(LC)/(2*pi)'],0,'f_res = 1/(2*pi*sqrt(LC)).','Medium','Resonance'),
  q('q7_12','ch7','Wattless component of current in AC circuit:',['Irms*cos(phi)','Irms*sin(phi)','Irms*tan(phi)','Irms'],1,'Wattless = I*sin(phi), contributes no power.','Hard','Power Factor'),
  q('q7_13','ch7','Phase angle in LCR circuit:',['tan(phi)=XL/R','tan(phi)=(XL-XC)/R','tan(phi)=R/(XL-XC)','tan(phi)=XC/R'],1,'tan(phi) = (XL-XC)/R.','Medium','LCR Circuit'),
  q('q7_14','ch7','Choke coil is used to:',['Increase current','Reduce current in AC','Store charge','Generate EMF'],1,'Choke coil (inductor) reduces AC current without power loss.','Easy','Impedance'),
  q('q7_15','ch7','Frequency of AC mains in India:',['50 Hz','60 Hz','100 Hz','25 Hz'],0,'AC mains in India is 50 Hz.','Easy','AC Voltage'),

  // Ch8: Electromagnetic Waves
  q('q8_1','ch8','EM waves were predicted by:',['Faraday','Ampere','Maxwell','Hertz'],2,'Maxwell predicted EM waves from his equations.','Easy','Maxwell Equations'),
  q('q8_2','ch8','EM waves are produced by:',['Stationary charges','Charges at rest','Accelerated charges','Uniform velocity charges'],2,'Accelerated charges produce EM waves.','Medium','EM Wave Propagation'),
  q('q8_3','ch8','Speed of EM waves in vacuum:',['3 x 10^8 m/s','3 x 10^6 m/s','3 x 10^10 m/s','3 x 10^5 m/s'],0,'c = 3 x 10^8 m/s in vacuum.','Easy','Properties of EM Waves'),
  q('q8_4','ch8','Which EM wave has highest frequency?',['Radio waves','Microwaves','Gamma rays','Infrared'],2,'Gamma rays have the highest frequency.','Easy','EM Spectrum'),
  q('q8_5','ch8','EM wave used in RADAR:',['Infrared','Ultraviolet','Microwave','X-ray'],2,'Microwaves are used in RADAR.','Easy','EM Spectrum'),
  q('q8_6','ch8','Infrared radiation is detected by:',['Photographic plate','Thermopile','GM counter','Human eye'],1,'Infrared detected by thermopile (heating effect).','Medium','EM Spectrum'),
  q('q8_7','ch8','Displacement current is:',['epsilon_0 * d(phi_E)/dt','mu_0 * d(phi_B)/dt','epsilon_0 * d(phi_B)/dt','mu_0 * d(phi_E)/dt'],0,'Id = epsilon_0 * d(phi_E)/dt.','Hard','Maxwell Equations'),
  q('q8_8','ch8','X-rays are used in:',['Radio communication','Medical imaging','Cooking','Remote controls'],1,'X-rays widely used in medical imaging.','Easy','EM Spectrum'),
  q('q8_9','ch8','Oscillating fields in EM wave are:',['Parallel','Perpendicular to each other and propagation direction','Along propagation','Random'],1,'E and B perpendicular to each other and to propagation direction.','Medium','Properties of EM Waves'),
  q('q8_10','ch8','Which is NOT an EM wave?',['Radio wave','Sound wave','X-ray','Gamma ray'],1,'Sound waves are mechanical, not electromagnetic.','Easy','EM Spectrum'),

  // Ch9: Ray Optics
  q('q9_1','ch9','Image formed by plane mirror is:',['Real and inverted','Virtual and erect','Real and erect','Virtual and inverted'],1,'Plane mirror: virtual, erect, same size image.','Easy','Reflection'),
  q('q9_2','ch9','Focal length of concave mirror is:',['Positive','Negative','Zero','Infinite'],1,'By sign convention, concave mirror focal length is negative.','Medium','Reflection'),
  q('q9_3','ch9','Snell law of refraction:',['n1*sin(i) = n2*sin(r)','n1*cos(i) = n2*cos(r)','n1*sin(r) = n2*sin(i)','n1*tan(i) = n2*tan(r)'],0,'Snell law: n1*sin(i) = n2*sin(r).','Easy','Refraction'),
  q('q9_4','ch9','Total internal reflection occurs when:',['Light goes denser to rarer at angle > critical angle','Rarer to denser','Angle of incidence is zero','Light perpendicular to surface'],0,'TIR: denser to rarer medium, angle > critical angle.','Medium','Total Internal Reflection'),
  q('q9_5','ch9','Power of lens with focal length 20 cm:',['+5 D','+20 D','-5 D','+0.05 D'],0,'P = 1/f = 1/0.2 = +5 D.','Easy','Lenses'),
  q('q9_6','ch9','Object at 2f of convex lens. Image is:',['At 2f, real, inverted, same size','At f, diminished','At infinity','Virtual, erect, magnified'],0,'Object at 2f: image at 2f, real, inverted, same size.','Medium','Lenses'),
  q('q9_7','ch9','Optical fibers work on:',['Refraction','Diffraction','Total internal reflection','Interference'],2,'Optical fibers use TIR to transmit light.','Easy','Total Internal Reflection'),
  q('q9_8','ch9','Magnifying power of simple microscope (image at near point):',['1 + D/f','D/f','f/D','1 + f/D'],0,'M = 1 + D/f.','Medium','Optical Instruments'),
  q('q9_9','ch9','Dispersion of light is due to:',['Reflection','Refraction','Wavelength-dependent speed in medium','Diffraction'],2,'Different wavelengths have different speeds in a medium.','Medium','Dispersion'),
  q('q9_10','ch9','Mirror equation:',['1/f = 1/v + 1/u','f = v + u','1/f = v + u','f = 1/v + 1/u'],0,'Mirror formula: 1/f = 1/v + 1/u.','Easy','Reflection'),
  q('q9_11','ch9','Convex lens has focal length:',['Positive','Negative','Zero','Infinite'],0,'Convex lens focal length is positive.','Easy','Lenses'),
  q('q9_12','ch9','Critical angle for material with n=2:',['30 degrees','45 degrees','60 degrees','90 degrees'],0,'sin(C) = 1/n = 1/2. C = 30 degrees.','Medium','Total Internal Reflection'),
  q('q9_13','ch9','Ray through center of curvature of concave mirror:',['Reverses along same path','Passes through focus','Parallel to axis','Refracted'],0,'Ray through C retraces its path.','Easy','Reflection'),
  q('q9_14','ch9','Angular dispersion is difference between:',['Deviation of red and violet','Red and green','Blue and red','Refraction angles'],0,'Angular dispersion = delta_violet - delta_red.','Medium','Dispersion'),
  q('q9_15','ch9','Compound microscope has:',['Two convex lenses','Two concave lenses','One convex one concave','One convex lens'],0,'Compound microscope: two convex lenses (objective + eyepiece).','Easy','Optical Instruments'),

  // Ch10: Wave Optics
  q('q10_1','ch10','In Young double slit experiment, fringe width:',['lambda*D/d','lambda*d/D','lambda*D^2/d','lambda^2*D/d'],0,'beta = lambda*D/d.','Easy','Interference'),
  q('q10_2','ch10','Constructive interference condition:',['Path diff = n*lambda','Path diff = (2n+1)*lambda/2','Path diff = lambda/4','Path diff = 0'],0,'Constructive: path difference = n*lambda.','Medium','Interference'),
  q('q10_3','ch10','Diffraction is maximum when slit width is:',['Very large','Very small','Equal to wavelength','Zero'],1,'Diffraction max when slit width comparable to or smaller than wavelength.','Medium','Diffraction'),
  q('q10_4','ch10','Brewster angle relates to refractive index by:',['tan(iB) = n','sin(iB) = n','cos(iB) = n','tan(iB) = 1/n'],0,'Brewster law: tan(iB) = n.','Medium','Polarization'),
  q('q10_5','ch10','Polarization proves light is:',['Longitudinal wave','Transverse wave','Mechanical wave','Standing wave'],1,'Only transverse waves can be polarized.','Easy','Polarization'),
  q('q10_6','ch10','Malus law: I = I0 * :',['sin^2(theta)','cos^2(theta)','tan^2(theta)','cos(theta)'],1,'Malus law: I = I0 * cos^2(theta).','Medium','Malus Law'),
  q('q10_7','ch10','In single slit diffraction, central maximum is:',['Narrowest','Widest','Same width as others','Absent'],1,'Central maximum is the widest.','Medium','Diffraction'),
  q('q10_8','ch10','If wavelength in YDSE is increased, fringe width:',['Increases','Decreases','Same','Zero'],0,'beta = lambda*D/d. lambda increases, beta increases.','Easy','Interference'),
  q('q10_9','ch10','Coherent sources can be obtained by:',['Two independent sources','Wavefront division','Amplitude division','Both B and C'],3,'Coherent sources: wavefront division (YDSE) or amplitude division (thin films).','Hard','Interference'),
  q('q10_10','ch10','A wavefront is locus of points with same:',['Amplitude','Frequency','Phase','Intensity'],2,'Wavefront: locus of points with same phase.','Easy','Wave Properties'),
  q('q10_11','ch10','Huygens principle explains:',['Reflection and refraction','Interference only','Diffraction only','Polarization only'],0,'Huygens principle explains reflection, refraction, diffraction.','Medium','Wave Properties'),
  q('q10_12','ch10','Resolving power of microscope increases with:',['Larger wavelength','Smaller wavelength','Larger aperture','Lower magnification'],1,'RP increases with smaller wavelength.','Medium','Diffraction'),
  q('q10_13','ch10','If slit distance in YDSE is doubled, fringe width:',['Doubles','Halves','Quadruples','Same'],1,'beta = lambda*D/d. d doubles, beta halves.','Easy','Interference'),
  q('q10_14','ch10','Intensity at maxima in interference of two equal sources:',['2*I0','4*I0','I0','I0/2'],1,'At maxima, I = (2A)^2 = 4*I0.','Medium','Interference'),
  q('q10_15','ch10','Polaroid reduces unpolarized light intensity to:',['Half','Zero','Full','One-fourth'],0,'Polaroid: I = I0/2 for unpolarized light.','Easy','Polarization'),

  // Ch11: Dual Nature
  q('q11_1','ch11','Photoelectric effect was explained by:',['Newton','Einstein','Bohr','Rutherford'],1,'Einstein explained photoelectric effect using photons.','Easy','Photoelectric Effect'),
  q('q11_2','ch11','Work function of a metal is:',['Min energy to remove electron','Max energy of photon','KE of electron','PE of electron'],0,'Work function = minimum energy to eject electron.','Medium','Photoelectric Effect'),
  q('q11_3','ch11','Einstein photoelectric equation:',['KE = hf - phi','KE = hf + phi','KE = phi - hf','KE = hf * phi'],0,'KE_max = hf - phi.','Medium','Einstein Equation'),
  q('q11_4','ch11','De Broglie wavelength of particle with momentum p:',['h/p','hp','p/h','h^2/p'],0,'lambda = h/p.','Easy','de Broglie Wavelength'),
  q('q11_5','ch11','Stopping potential depends on:',['Intensity of light','Frequency of light','Both','Neither'],1,'Stopping potential depends on frequency, not intensity.','Medium','Photoelectric Effect'),
  q('q11_6','ch11','If frequency is below threshold:',['Electrons emitted slowly','No electrons emitted','More electron energy','Photons reflected'],1,'Below threshold, no photoelectrons regardless of intensity.','Easy','Photoelectric Effect'),
  q('q11_7','ch11','De Broglie wavelength of electron accelerated through V volts:',['1.227/sqrt(V) nm','12.27/sqrt(V) nm','122.7/sqrt(V) nm','0.1227/sqrt(V) nm'],0,'lambda = 1.227/sqrt(V) nm for electron.','Medium','de Broglie Wavelength'),
  q('q11_8','ch11','Wave-particle duality means:',['Light is only wave','Matter is only particle','Both light and matter show wave and particle nature','Neither'],2,'Duality applies to both light and matter.','Easy','Wave-Particle Duality'),
  q('q11_9','ch11','Photoelectric current is proportional to:',['Frequency','Intensity','Wavelength','Speed of light'],1,'Current proportional to intensity (photon count).','Easy','Photoelectric Effect'),
  q('q11_10','ch11','Electron and proton with same de Broglie wavelength. Which has more KE?',['Electron','Proton','Same KE','Cannot determine'],0,'Same lambda = same p. KE = p^2/(2m). Smaller m = more KE.','Hard','de Broglie Wavelength'),

  // Ch12: Atoms
  q('q12_1','ch12','In Bohr model, radius of nth orbit is proportional to:',['n','n^2','1/n','1/n^2'],1,'r_n proportional to n^2.','Easy','Bohr Model'),
  q('q12_2','ch12','Energy of electron in nth Bohr orbit:',['-13.6/n eV','-13.6*n eV','-13.6/n^2 eV','-13.6*n^2 eV'],2,'E_n = -13.6/n^2 eV.','Medium','Energy Levels'),
  q('q12_3','ch12','Lyman series corresponds to transitions ending at:',['n=1','n=2','n=3','n=4'],0,'Lyman series: transitions to n=1 (UV).','Easy','Atomic Spectra'),
  q('q12_4','ch12','Balmer series is in the:',['Ultraviolet','Visible','Infrared','X-ray'],1,'Balmer series (to n=2) is in visible region.','Easy','Atomic Spectra'),
  q('q12_5','ch12','First Bohr radius (a0) is:',['0.53 angstrom','5.3 angstrom','0.053 angstrom','53 angstrom'],0,'a0 = 0.53 angstrom.','Medium','Bohr Model'),
  q('q12_6','ch12','Angular momentum in Bohr model:',['L = nh','L = nh/(2*pi)','L = n^2*h','L = h/n'],1,'L = n*h/(2*pi).','Medium','Bohr Model'),
  q('q12_7','ch12','Rutherford experiment led to discovery of:',['Electron','Proton','Nucleus','Neutron'],2,'Rutherford discovered the nucleus.','Easy','Hydrogen Atom'),
  q('q12_8','ch12','Paschen series corresponds to:',['n=1','n=2','n=3','n=4'],2,'Paschen series: transitions to n=3 (IR).','Easy','Atomic Spectra'),
  q('q12_9','ch12','Shortest wavelength in Lyman series:',['121.6 nm','656.3 nm','364.6 nm','91.2 nm'],3,'Lyman limit (infinity to n=1): lambda = 91.2 nm.','Hard','Atomic Spectra'),
  q('q12_10','ch12','Total energy of hydrogen atom in ground state:',['-13.6 eV','+13.6 eV','-3.4 eV','0 eV'],0,'Ground state (n=1): E = -13.6 eV.','Easy','Energy Levels'),

  // Ch13: Nuclei
  q('q13_1','ch13','Size of a nucleus is of order:',['10^-10 m','10^-15 m','10^-8 m','10^-12 m'],1,'Nuclear size ~ femtometers (10^-15 m).','Easy','Nuclear Structure'),
  q('q13_2','ch13','Isotopes have same:',['Mass number','Atomic number','Neutrons','Binding energy'],1,'Isotopes: same Z, different A.','Easy','Nuclear Structure'),
  q('q13_3','ch13','Radioactivity was discovered by:',['Becquerel','Curie','Rutherford','Bohr'],0,'Becquerel discovered radioactivity (1896).','Easy','Radioactivity'),
  q('q13_4','ch13','In alpha decay, atomic number:',['Increases by 2','Decreases by 2','Increases by 4','Decreases by 4'],1,'Alpha decay: Z decreases by 2, A decreases by 4.','Medium','Radioactivity'),
  q('q13_5','ch13','In beta-minus decay, neutron converts to:',['Proton + electron','Proton + positron','Electron + positron','Proton only'],0,'Beta-minus: n -> p + e- + anti-neutrino.','Medium','Radioactivity'),
  q('q13_6','ch13','Half-life is time for:',['All atoms to decay','Half the atoms to decay','One atom to decay','Activity to double'],1,'Half-life: time for half of atoms to decay.','Easy','Half Life'),
  q('q13_7','ch13','Nuclear fission is:',['Combining small nuclei','Splitting heavy nucleus','Emitting alpha particles','Absorbing electrons'],1,'Fission: splitting heavy nucleus into lighter ones.','Easy','Nuclear Fission'),
  q('q13_8','ch13','Nuclear fusion occurs in:',['Nuclear reactors','Stars','X-ray tubes','Particle accelerators'],1,'Fusion powers stars including our Sun.','Easy','Nuclear Fusion'),
  q('q13_9','ch13','Mass defect relates to binding energy by:',['E = mc^2','E = mgh','E = (1/2)mv^2','E = hf'],0,'E = delta(m)*c^2.','Easy','Mass-Energy Relation'),
  q('q13_10','ch13','Isobars have same:',['Z','A','Neutrons','Binding energy per nucleon'],1,'Isobars: same mass number A, different Z.','Medium','Nuclear Structure'),
  q('q13_11','ch13','Binding energy per nucleon is maximum for:',['Hydrogen','Uranium','Iron (Fe-56)','Helium'],2,'Fe-56 has maximum binding energy per nucleon.','Medium','Mass-Energy Relation'),
  q('q13_12','ch13','After 3 half-lives, remaining fraction:',['1/2','1/4','1/8','1/16'],2,'(1/2)^3 = 1/8.','Easy','Half Life'),
  q('q13_13','ch13','Energy released in U-235 fission per nucleus:',['200 MeV','200 eV','200 keV','200 GeV'],0,'Each U-235 fission releases ~200 MeV.','Medium','Nuclear Fission'),
  q('q13_14','ch13','Gamma rays are:',['Fast electrons','High energy photons','Slow neutrons','Helium nuclei'],1,'Gamma rays are high-energy EM photons from nuclei.','Easy','Radioactivity'),
  q('q13_15','ch13','Nuclear density is approximately:',['2.3 x 10^17 kg/m^3','2.3 x 10^7 kg/m^3','2.3 x 10^27 kg/m^3','2.3 x 10^-17 kg/m^3'],0,'Nuclear density ~ 2.3 x 10^17 kg/m^3 (constant for all nuclei).','Hard','Nuclear Structure'),

  // Ch14: Semiconductors
  q('q14_1','ch14','Pure semiconductor at 0K behaves as:',['Conductor','Insulator','Superconductor','Semimetal'],1,'At 0K, pure semiconductor has no free carriers (insulator).','Easy','Intrinsic Semiconductor'),
  q('q14_2','ch14','In n-type semiconductor, majority carriers:',['Holes','Electrons','Protons','Neutrons'],1,'N-type: electrons are majority carriers.','Easy','Extrinsic Semiconductor'),
  q('q14_3','ch14','In p-type semiconductor, majority carriers:',['Electrons','Holes','Neutrons','Protons'],1,'P-type: holes are majority carriers.','Easy','Extrinsic Semiconductor'),
  q('q14_4','ch14','A p-n junction allows current in:',['Both directions','Forward bias only','Reverse bias only','Neither'],1,'PN junction conducts in forward bias only.','Easy','p-n Junction'),
  q('q14_5','ch14','Depletion layer forms due to:',['External voltage','Diffusion of carriers','Temperature effect','Magnetic field'],1,'Depletion layer from diffusion of majority carriers.','Medium','p-n Junction'),
  q('q14_6','ch14','In forward bias, depletion layer:',['Widens','Narrows','Same','Disappears'],1,'Forward bias: depletion layer narrows.','Medium','p-n Junction'),
  q('q14_7','ch14','Barrier potential of silicon p-n junction:',['0.3 V','0.7 V','1.1 V','0 V'],1,'Si barrier potential ~ 0.7 V.','Easy','p-n Junction'),
  q('q14_8','ch14','Zener diode is used as:',['Rectifier','Amplifier','Voltage regulator','Oscillator'],2,'Zener diode: voltage regulator in reverse breakdown.','Medium','Diode'),
  q('q14_9','ch14','Full-wave rectifier uses:',['1 diode','2 diodes','3 diodes','4 diodes'],1,'Full-wave rectifier: 2 diodes (or bridge with 4).','Easy','Diode'),
  q('q14_10','ch14','AND gate output is HIGH when:',['Both inputs HIGH','At least one HIGH','No input HIGH','Any one LOW'],0,'AND: HIGH only when both inputs HIGH.','Easy','Logic Gates'),
  q('q14_11','ch14','OR gate output is LOW when:',['Both inputs LOW','Both HIGH','One HIGH','Any LOW'],0,'OR: LOW only when both inputs LOW.','Easy','Logic Gates'),
  q('q14_12','ch14','NOT gate is also called:',['AND gate','OR gate','Inverter','NAND gate'],2,'NOT gate = inverter.','Easy','Logic Gates'),
  q('q14_13','ch14','In a transistor, the base region is:',['Very heavily doped','Very thin and lightly doped','Moderately doped','Not doped'],1,'Base is thin and lightly doped.','Medium','Transistor'),
  q('q14_14','ch14','Current gain beta of transistor:',['Ic/Ib','Ib/Ic','Ie/Ib','Ic/Ie'],0,'Beta = Ic/Ib (common emitter).','Medium','Transistor'),
  q('q14_15','ch14','LED works on:',['Thermionic emission','Spontaneous emission of light','Stimulated emission','Photoelectric effect'],1,'LED: spontaneous light emission at p-n junction.','Easy','Diode'),
];

export const defaultAdmin: Admin = {
  id: 'admin-001', name: 'Admin', email: 'admin@nathans.com', password: 'admin123', createdAt: '2024-01-01T00:00:00.000Z',
};

export const defaultSettings: Settings = {
  passPercentage: 40, questionsPerChapter: 10, timerEnabled: false, timerMinutes: 15,
  schoolName: 'Nathan Physics Academy', certificateTitle: 'Certificate of Completion',
  certificateStatement: 'has successfully completed all chapters of Nathan Physics MCQ',
  leaderboardEnabled: true, allowRetest: true,
};